base_de_datos_url = 'recursos/db.json'
codigo_de_inicio = '0000000'
membrete_height = 32
membrete_pos_x = 65
membrete_url = 'recursos/imagenes/membrete'
razon_social = 'de Pepito'
datos_razon_social_linea1 = 'WhatsApp : 11-1111-1111'
datos_razon_social_linea2 = ''
datos_razon_social_linea3 = ''
membrete_extensiones = ['.jpg', '.png', '.gif']
nota_al_pie = 'Los montos detallados en este presupuesto sólamente serán válidos durante las próximas 72 Hs.'
